### ISSUE TITLE
undefined method `quoted_table_name' for Paperclip::Attachment:Class

### ISSUE THREAD

**Issue by lylo** [jstorimer/delayed_paperclip#1]
I'm running the latest master branch of Paperclip (as at 2nd Feb 10) and the 0.5.0 version of the delayed_paperclip gem, but when I add the 'process_in_background' call to my model (as described in the rdoc) I'm seeing this error:

```
undefined method `quoted_table_name' for Paperclip::Attachment:Class
vendor/rails/activerecord/lib/active_record/reflection.rb:187:in `quoted_table_name'
vendor/rails/activerecord/lib/active_record/associations/has_one_association.rb:90:in `construct_sql'
vendor/rails/activerecord/lib/active_record/associations/has_one_association.rb:6:in `initialize'
vendor/rails/activerecord/lib/active_record/associations.rb:1246:in `new'
vendor/rails/activerecord/lib/active_record/associations.rb:1246:in `attachment'
```

I'm running Rails 2.3.4.  Am I doing something wrong?

**Comment by jstorimer** [comment]
I ran into this once myself and the problem was that my model was named Style, and somehow my top-level constant Style was conflicting with Paperclip::Style.

I'm guessing your ActiveRecord model is named Attachment? I still haven't figured out how to fix this one, just wanted to let you know that I can confirm it and you're not doing something wrong.

**Comment by lylo** [comment]
Yup, the model is indeed called Attachment.  I've been considering renaming it anyway as seeing attachment.attachment in the code really bothers me!

**Comment by jstorimer** [comment]
This is actually a problem with Paperclip in general. The fix is here: http://thewebfellas.com/blog/2008/11/2/goodbye-attachment_fu-hello-paperclip#comment-2415
