### ISSUE TITLE
Mongoid compatibility ticket

### ISSUE THREAD

**Issue by masterkain** [jstorimer/delayed_paperclip#25]
Hello,
I'm trying to use delayed_paperclip with Mongoid and Resque, definitely there are some key points that we have to adjust to make the gem play nice with Mongoid.

1) Instance ids
https://github.com/jstorimer/delayed_paperclip/blob/master/lib/delayed/paperclip.rb#L30

Here for both delayed_job and resque we do read_attribute(:id). The problem is that while Mongoid supports the read_attribute method, :id doesn't return what we expect, it returns nil. Either we have to call .id directly or read_attribute(:_id).to_s

2) column_exists? method fault
https://github.com/jstorimer/delayed_paperclip/blob/master/lib/delayed/paperclip.rb#L83

In Mongoid it should be something like:

```
self.class.fields.keys.include?(column.to_s)
```

I'm currently looking for other problems, to make the gem compatible an effort should be made with some conditionals.

**Comment by bigfleet** [comment]
If this issue is merged, I feel the README should at least include some reference to the [Mongoid thread on safe writes](http://groups.google.com/group/mongoid/browse_thread/thread/a6901b42420a6459?pli=1) and/or [Mongo durability](http://www.mongodb.org/display/DOCS/Durability+and+Repair).  Users should be aware of the increased possibility of a job queueing failure without these options.

**Comment by jstorimer** [comment]
@bigfleet Good call.

Isn't Paperclip compatible with Mongoid? They must deal with these issues.

**Comment by bigfleet** [comment]
@jstorimer Great idea.

This seems to be an issue that the Paperclip team isn't taking on directly.  The writings I've found seem to focus on getting the logger changed, so that mongoid can be used at all, with little or no further discussion.

I think that's OK-- imagine the user of a library.  Without delayed_paperclip, they'd see immediately if it worked or didn't and why.  Perhaps delayed_paperclip getting involved in the process means we have extra responsibility, but perhaps not.

**Comment by jstorimer** [comment]
Looks like Mongoid compatibility exists in a separate gem (https://github.com/meskyanichi/mongoid-paperclip). I'm not crazy about changing delayed_paperclip to support Mongoid given that Paperclip doesn't support it directly.

Closing for now.

**Comment by kellym** [comment]
Just FYI @masterkain I pushed out a new gem today for those of us using Mongoid and Resque with Paperclip called [mongoid_paperclip_queue](http://github.com/kellym/mongoid_paperclip_queue). I'm not guaranteeing it solves all your problems, but it's a start.
