### ISSUE TITLE
failed with RuntimeError: cannot generate tempfile `/tmp/...

### ISSUE THREAD

**Issue by mtunjic** [jstorimer/delayed_paperclip#41]
my config:
has_attached_file :data,
                    :storage => :ftp,
                    :url => /:attachment/:style/:filename",
                    :path => "/var/www/ais/public/assets/:attachment/:style/:filename",
                    :ftp_credentials => Rails.root.join('config', 'paperclipftp.yaml')

Any Suggestions?

**Comment by kredmer** [comment]
the problem live in paperclip/storage "to_file" method (depending on your storage!!!)

in my case I use S3 with eu-buckets and there was following defined:
(in s3_paperclip.rb in config/initializers)
def to_file style = default_style
....
 file = Tempfile.new(path(style)) # this made my error !!!
....
end

I changed the line to: file = Tempfile.new(style)
(because Tempfile don't like the path in the name - should be a second argument - but you don't need it because every file get a unique name ending)

This solved my problem and I love delayed_paperclip !

**Comment by Bertg** [comment]
@kredmer Maybe you could add this as a patch for paperclip?

@attractor Is this issue also occurring if you are not using delayed_paperclip? If so, it's probably not something this gem can fix for you.

**Comment by kredmer** [comment]
It is not a paperclip problem - paperclip uses normally aws-s3
I use this combo for getting s3-eu-bucket-support and some paperclip fixes:
gem 'paperclip', :git => "git://github.com/jeanmartin/paperclip.git", :branch => "master" 
gem "s3", "0.3.8"
gem 'delayed_paperclip', "0.6.5"

@attractor: did you solve it?

**Comment by Bertg** [comment]
We do not support unofficial paperclip branches. Also, the version you are using hasn't been updated since April, you might want to check the more recent versions of paperclip ;)

**Comment by kredmer** [comment]
The new versions didn't work for me. This one fixed some problems the newer versions havn't - and delayed_paperclip is working.
