### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by Bertg** [jstorimer/delayed_paperclip#46]
Hey all interested,

I was thinking about changing the versioning of this gem. Why you ask? Well, 
- there have been quite some questions about what versions of delayed_paperclip are compatible with what versions of paperclip
- paperclip has been moving really fast lately, and it has become a pain to keep one version of delayed_paperclip compatible with several versions of paperclip
- testing against multiple versions of paperclip, and the multiple versions of rails/ruby paperclip supports, plus testing against multiple versions of delayed_job and resque just becomes hell

So what do I propose? We number this gem exactly as paperclip. So:
- For each paperclip release, there will be a delayed_paperclip release (solves the issues above)
- New delayed_paperclip features will only be added to the latest version

But there is still one issue here: How do we handle bugfix releases within one version of paperclip? I would suggest using a 4 number version: 2.3.4.0 where the last number would reflect a bugfix release of delayed_paperclip. I think this is compatible with rubygems.

What do you think?

**Comment by jstorimer** [comment]
I personally don't have a problem with this, but I don't envy the guy who is responsible for releasing new versions of dp.

For example, there have been 4 releases of paperclip since the last commit was made to dp. Someone would need to step up whenever a new version of paperclip has been released, run the tests, (make the fixes), and push a new version. I'm personally not able to commit to Paperclip's schedule. If you can then I'm behind you 100%.

I think the versioning scheme you mentioned is sensical (and compatible with Rubygems) the only issue is that it can quickly fall out of date with what Paperclip has. As I mentioned Paperclip has had 4 releases since dp was last released. Would that mean that the current version of dp is incompatible with the current version of Paperclip? Maybe it is compatible? But noone bumped the version.

I think you see what I'm getting at. And I totally respect wanting to get out of testing hell, that's the only way this thing can continue to be maintained.

What about opening an issue (or better yet a pull request!) when a new version of Paperclip is released, so that folks are notified that there's work to be done?

**Comment by Bertg** [comment]
I would define each dp release to be dependant on the paperclip version, or larger. This would allow the gem to be used with later versions as well.

Keeping up should not be to difficult. I'll create a small task that will automatically update the dependancies, and run the tests. If the tests are green we should be able to push a new version. I could commit to this on a weekly basis.

**Comment by jstorimer** [comment]
+1

**Comment by tommeier** [comment]
+1

**Comment by atd** [comment]
+1

**Comment by Bertg** [comment]
It has been done. Release 2.4.[0-5].0 today. Let me know how it works out for you.
