### ISSUE TITLE
New version appears to break passenger rails

### ISSUE THREAD

**Issue by dreamwieber** [jstorimer/delayed_paperclip#6]
When trying to start my rails app (passenger,  ruby enterprise),  I get this error:
undefined method `url' for class`Paperclip::Attachment'

The issue is solved by reverting to the earlier release of delayed_paperclip.

**Comment by jstorimer** [comment]
I think this is because delayed_paperclip tries to alias_method_chain a method in Paperclip::Attachment but it wasn't properly requiring 'paperclip' on load, so you had to manage the load order of libraries yourself.

I added "require 'paperclip'" when loading the plugin and bumped the version to 0.6.3. Let me know if this fixed the issue for you.
